name: packaging
on: push
jobs:
  linux:
    name: Create linux binary package
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install external dependencies
        run: |
          sudo apt install -y libsdl2-dev libsdl2-image-dev gifsicle

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run packaging
        run: |
          poetry run invoke package

  osx:
    name: Create OSX binary package
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install external dependencies
        run: |
          brew install gcc sdl2 sdl2_image gifsicle

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run packaging
        run: |
          poetry run invoke package
